### ISSUE TITLE
Support exporting more than one path

### ISSUE THREAD

**Issue by ergo123** [Cognifide/crex-sdk#13]
Creative exchange supports exporting many paths. crex should also let do this.

E.g. this doesn't work:
`ce export -x folder path1/subpath1,path2/subpath2`
It throws an error:
```
(node:16044) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'status' of undefined
(node:16044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Running export separately for each path works correctly:
`ce export -x folder path1/subpath1`
`ce export -x folder path2/subpath2`

**Comment by mateuszluczak** [comment]
#15

**Comment by ergo123** [comment]
Thanks @mateuszluczak, that were really quick fixes.
