### ISSUE TITLE
Add multiple filters

### ISSUE THREAD

**Issue by mcarneiro** [Cognifide/crex-sdk#2]
While using `ce` I was always filtering the `content` folder as it's the most constantly updated place, but sometimes I need to update other places, such as `etc/designs/zg/avada/desktop/css/core` or `etc/designs/zg-layout`, for example. We would need to be able to pass multiple filters, maybe something like accepting filter parameters multiple times:

```
$ ce export content/blueprints/author/avada/default/en-us/ -x -f content -f etc/designs/zg/avada/desktop/css/core
```

Or multiple values to filter param:

```
$ ce export content/blueprints/author/avada/default/en-us/ -x -f content,etc/designs/zg/avada/desktop/css/core
```

**Comment by mateuszluczak** [comment]
Hello Marcelo,

Thanks for the enhancement - seems like a useful feature.
I've already implemented it - release **1.2.1** has ability to pass comma separated list of filters.
