### ISSUE TITLE
Error or warning feedbacks

### ISSUE THREAD

**Issue by mcarneiro** [Cognifide/crex-sdk#3]
I noticed that when there's any issue when installing or inspecting the package there's no error output telling what hapenned. The output will be empty and stay as:

```
Auth file found
✔ Package ce-import.zip installed on localhost:4502
```

It happened with me when I tried to update a protected theme.

**Comment by mateuszluczak** [comment]
<img width="683" alt="screen shot 2017-08-31 at 16 29 04" src="https://user-images.githubusercontent.com/2010759/29928548-979fe1d8-8e69-11e7-80e6-2774c1763584.png">

Hey @mcarneiro I've added error and warnings handling in version **1.3.0**
