### ISSUE TITLE
Crex doesn't work behind proxy

### ISSUE THREAD

**Issue by mcarneiro** [Cognifide/crex-sdk#4]
Maybe this would be the answer for crex not working behind a proxy: https://github.com/TooTallNate/superagent-proxy

I would consider using `https_proxy` and `http_proxy` env variables to match unix way of work. If I get time to fix it, I can make a PR on this one.

**Comment by mateuszluczak** [comment]
Hey @mcarneiro,

Thanks for posting this issue - `superagent-proxy` looks like solution.
If you could create a PR with the fix it would be great, if not I may have some time end of this week or next week to fix it.

Cheers

**Comment by mcarneiro** [comment]
Hey @mateuszluczak, created this PR with a quick fix for proxy: https://github.com/Cognifide/crex-sdk/pull/5

**Comment by mateuszluczak** [comment]
Released in 1.5.0
